export default function Head() {
  return (
    <>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      {/* <link rel="icon" href="/favicon.ico" /> */}
      <link rel="icon" href="/images/logo.png"></link>
      <title>MNP</title>
    </>
  );
}
